version: '3.4'

services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    ports:
      - "8000:8000"
      - "8443:8443"
      - "9901:9901"
    volumes:
      - ./deployment/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
         - public.frontend

  public.frontend:
    image: ${DOCKER_REGISTRY-}publicfrontend
    build:
      context: .
      dockerfile: Public.Frontend/Dockerfile
 

