version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
 
  # proxy-endpoint:
  #     image: ${DOCKER_REGISTRY-}agentproxyendpoint
  #     build:
  #      context: ./AgentProxy
  #      dockerfile: ./AgentProxy.Endpoint/Dockerfile   